# Generated by Django 3.1.4 on 2020-12-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearch', '0004_querydailyhits_verbose_name_plural'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='querydailyhits',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='querydailyhits',
            name='query',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryDailyHits',
        ),
    ]
