# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 15:37
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentry',
            name='body_partials_search',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
            preserve_default=False,
        ),
    ]
