# Generated by Django 2.2.10 on 2020-07-13 10:13

from django.db import migrations, models
import wagtail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0046_site_name_remove_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'language_code'],
            },
            managers=[
                ('objects', wagtail.core.models.LocaleManager()),
            ],
        ),
    ]
