# Generated by Django 3.1.8 on 2021-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0063_pagepatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerevision',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='pagerevision',
            constraint=models.UniqueConstraint(condition=models.Q(is_draft=True), fields=('page_id',), name='unique_draft_revision'),
        ),
    ]
